# Site settings
title: Predictors of Permanent Housing for Homeless Families
email: arokem@gmail.com
description: ""
baseurl: "http://uwescience.github.io/DSSG2015-predicting-permanent-housing"
url: "http://uwescience.github.io/DSSG2015-predicting-permanent-housing"
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
