# Site settings
title: Data Science for Social Good 2015
email: arokem@gmail.com
description: ""
baseurl: "http://uwescience.github.io/DSSG2015-predicting-permanent-housing"
url: "http://uwescience.github.io/DSSG2015-predicting-permanent-housing"
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
